### ISSUE TITLE
Windpower generator

### ISSUE THREAD

**Issue by MrGreenball** [cyblabs/xlab#10]
- [x] Find Project OpenS: [1](https://www.thingiverse.com/thing:948401), [2](https://www.thingiverse.com/thing:911735), [3](https://www.thingiverse.com/thing:2851306)
 - [ ] Printing 
 - [ ] Buy and Delivery components
 - [ ] Assembly 
 - [ ] Test

**Comment by xhipster** [comment]
I am more inspired by vertical designs like [Mk2](https://www.thingiverse.com/thing:948401), but it is just intuitive.

**Comment by xhipster** [comment]
Merged with https://github.com/cyblabs/xlab/issues/15
