### ISSUE TITLE
Coders tasks

### ISSUE THREAD

**Issue by MrGreenball** [cyblabs/xlab#17]
Необходимо понимание железяк, таких как, Arduino, Raspberry и сенсорам к ним. 
 Задачи для выполнения : 
  -  Разработка Вэб интерфейса (простейшего) 
  -  Прошивка для Arduino (работа с 3-мя осями xyz, считывание данных сенсоров)
  -  Прошивка(или отдельный образ Raspbian) Raspberry для управления Arduino

Концепт :
 Визуализированное поле , с выбором кол-ва рабочих точек и расстояния между ними. 
К точкам возможность применить (прикреплять, откреплять) данные библиотеки.  
В данных хранятся команды для действия по сенсорам. 
К каждой точке до 10 действий(или больше) . 
Малина обеспечивает управление Ардуиной при помощи веб интерфейса (с возможностью описанной выше).
Ардуина управляет моторами и общается с сенсорами.

**Comment by MrGreenball** [comment]
Я думаю что прога с такой логикой подойдет для любого агрегата которому нужно "обрабатывать" определенную координату. Например имея руку-манипулятор можно описать ей алгоритм действия.

**Comment by xhipster** [comment]
Мне необходимо уточнение задачи. Возможно мы с @litvintech найдем софтверного инженера на совместные задачи для лаб. Но задача к этому моменту должна быть сформулирована.
