### ISSUE TITLE
Prepare roadmap and one year forecast

### ISSUE THREAD

**Issue by MrGreenball** [cybLabs/xlab#3]
## Forecast structure
- Purchases by projects 
- Salaries
- Rent

## Projects

- Skyminer
- Farmbot
- Farmbot killer
- Venera
- Brushes Motor
- Robohand  
- Printer SLA
- Printer DLA 
- Quadrocopter with FPV 180 mm 
- Windpower generator 
- Electro longboard 
- Cat autodoor and feeder and water   
- Personal robot helper
- Verteacal Drone charger
- HEP
- Aira Router 
- Smart socket

**Comment by xhipster** [comment]
To more projects:
- container mini prototype
- foam lighthouse

**Comment by xhipster** [comment]
Done
